// everything i've built, in one place. /software draws the entries that have
// a `canvas` placement as the canvas, in this order; /developer lists every
// entry under its `group`.
//
// an entry: `name`, `href`, a one-line `note`, `status` (null while it still
// runs, else how it ended) and `lang`, its main language. `repo` is the source when `href` is a
// product page. `canvas` places it on the 12-column canvas: `col` (grid
// columns), `drop` (rem from the row above), `x` (an optional sideways
// nudge in rem, for less than a column), and the poster's `w` x `h`
// (static/software/<name>.webp). `clip` plays static/previews/<name>.mp4 on
// hover; `phone` gives a phone recording a narrower frame with an iphone's corners
const GIT = "https://git.harivan.sh/harivansh-afk";

export const groups = {
  software: "things people use",
  tools: "for my own workflow",
  experiments: "built to learn, or to see if it works",
};

export const software = [
  {
    name: "mixbridge",
    lang: "swift",
    group: "software",
    href: "https://mixbridge.app/",
    note: "a beautiful listening experience for ios that mixes music on the go",
    status: null,
    canvas: { col: "2 / span 2", drop: 0, w: 590, h: 1280, phone: true, clip: true },
    alt: "mixbridge mixing between two tracks on an iphone",
  },
  {
    name: "touchtips",
    lang: "swift",
    group: "software",
    href: "https://touchtips.app",
    note: "remember when, where and who you met.",
    status: null,
    canvas: { col: "5 / span 5", drop: 3, w: 1280, h: 720, clip: true },
    alt: "touchtips open on a phone outdoors",
  },
  {
    name: "einstein",
    group: "software",
    href: "https://www.cnet.com/tech/services-and-software/companion-einstein-ai-tool/",
    note: "ai agent that does your homework autonomously",
    status: "cease and desisted :(",
    canvas: { col: "11 / span 2", drop: 7.5, w: 640, h: 400 },
    alt: "einstein's portrait on yellow",
  },
  {
    name: "draw",
    lang: "go",
    group: "software",
    href: `${GIT}/draw`,
    note: "self-hosted excalidraw with real-time collaboration and link sharing",
    status: null,
    canvas: { col: "1 / span 6", drop: 1.5, w: 1280, h: 536, clip: true },
    alt: "draw's dashboard of saved canvases",
  },
  {
    name: "roomcast",
    lang: "python",
    group: "software",
    href: `${GIT}/roomcast`,
    note: "play any movie, tv-show or music video under the sun, one text away",
    status: null,
    canvas: { col: "9 / span 2", drop: 0, w: 720, h: 1280, phone: true, clip: true },
    alt: "a telegram message asking an agent to resume a show",
  },
  {
    name: "mux",
    lang: "rust",
    group: "software",
    href: `${GIT}/mux`,
    note: "a stateless, host-agnostic, macos-native terminal multiplexing client for libghostty",
    status: null,
    canvas: { col: "3 / span 4", drop: -3.5, x: -1.5, w: 1184, h: 780, clip: true },
    alt: "mux running a nix build across panes",
  },
  {
    name: "deskctl",
    lang: "rust",
    group: "software",
    href: "https://deskctl.dev",
    repo: `${GIT}/deskctl`,
    note: "non-interactive x11 control cli",
    status: "no longer maintained",
    canvas: { col: "8 / span 5", drop: 0, w: 1280, h: 652, clip: true },
    alt: "an agent driving a linux desktop through deskctl",
  },
  {
    name: "nap",
    lang: "rust",
    group: "software",
    href: `${GIT}/nap`,
    note: "extend your mac's display to a linux machine (realtime)",
    status: null,
    canvas: { col: "2 / span 2", drop: 0, x: 3, w: 360, h: 640, phone: true, clip: true },
    alt: "nap casting a mac display to a wall monitor",
  },
  {
    name: "betternas",
    lang: "go",
    group: "software",
    href: "https://betternas.com",
    repo: `${GIT}/betterNAS`,
    note: "macos-native filesystem admin over http",
    status: "no longer maintained",
    canvas: { col: "5 / span 5", drop: 3.5, x: 3, w: 1280, h: 800, clip: true },
    alt: "betternas mounting a remote machine in finder",
  },
  {
    name: "pierrejo",
    lang: "javascript",
    group: "software",
    href: `${GIT}/pierrejo`,
    note: "beautiful, instantaneous diff viewing for forgejo",
    status: null,
    canvas: { col: "1 / span 5", drop: 1, w: 1280, h: 894, clip: true },
    alt: "pierrejo rendering a pull request diff in forgejo",
  },
  {
    name: "sharefs",
    lang: "rust",
    group: "software",
    href: `${GIT}/sharefs`,
    note: "browse files in the web ui or share them from the terminal. a fork of dufs.",
    status: null,
  },
  {
    name: "agentcomputer",
    group: "software",
    href: "https://github.com/AgentComputerAI",
    note: "isolated cloud computers for ai-agents",
    status: "no longer maintained",
    canvas: { col: "8 / span 4", drop: 4, w: 1280, h: 782, clip: true },
    alt: "agentcomputer's landing page",
  },
  {
    name: "airplay-at-the-crib",
    lang: "swift",
    group: "software",
    href: `${GIT}/airplay-at-the-crib`,
    note: "a mac app that puts roku tvs in screen mirroring on shared wi-fi.",
    status: null,
  },

  {
    name: "cozybox.nvim",
    lang: "lua",
    group: "tools",
    href: `${GIT}/cozybox.nvim`,
    note: "my neovim theme, dark and light. the code on this site wears it.",
    status: null,
  },
  {
    name: "pr.nvim",
    lang: "lua",
    group: "tools",
    href: `${GIT}/pr.nvim`,
    note: "review github and forgejo pull requests in neovim.",
    status: null,
  },
  {
    name: "sketchybar-feed",
    lang: "objective-c",
    group: "tools",
    href: `${GIT}/nix/src/branch/main/hosts/macbook/sketchybar-feed`,
    note: "the macbook's bar, pushed by system events instead of polled by scripts.",
    status: null,
  },
  {
    name: "linearjo",
    lang: "typescript",
    group: "tools",
    href: `${GIT}/linearjo`,
    note: "first-class linear integration for forgejo.",
    status: null,
  },
  {
    name: "sim",
    lang: "typescript",
    group: "tools",
    href: `${GIT}/sim`,
    note: "renders markdown and html in the terminal.",
    status: null,
  },
  {
    name: "tmux-subagents",
    lang: "shell",
    group: "tools",
    href: `${GIT}/tmux-subagents`,
    note: "orchestrates cli subagents through tmux windows.",
    status: null,
  },

  {
    name: "cas",
    lang: "rust",
    group: "experiments",
    href: `${GIT}/cas`,
    note: "content-addressed block storage for qemu.",
    status: null,
  },
  {
    name: "jarvis",
    lang: "go",
    group: "experiments",
    href: `${GIT}/jarvis`,
    note: "a voice interface to ongoing work on spark.",
    status: null,
  },
  {
    name: "game-theory",
    lang: "python",
    group: "experiments",
    href: `${GIT}/game-theory`,
    note: "a personal game-theory decision tool, version zero. no llm in the loop, deliberately.",
    status: null,
  },
  {
    name: "llt",
    lang: "svelte",
    group: "experiments",
    href: `${GIT}/llt`,
    note: "low-latency trading: a prediction-market gateway.",
    status: null,
  },
  {
    name: "agentikube",
    lang: "go",
    group: "experiments",
    href: `${GIT}/agentikube`,
    note: "stateful kubernetes pods for ai agents.",
    status: null,
  },
  {
    name: "computer-runtime",
    lang: "shell",
    group: "experiments",
    href: `${GIT}/computer-runtime`,
    note: "a nix bootstrap for declarative agent deployments on agentcomputer.",
    status: null,
  },
  {
    name: "url-shortner",
    lang: "python",
    group: "experiments",
    href: `${GIT}/url-shortner`,
    note: "a distributed url shortener, written by hand to practice programming in a world of ai slop.",
    status: null,
  },
  {
    name: "distributed-systems",
    group: "experiments",
    href: `${GIT}/distributed-systems`,
    note: "learning distributed systems through hands-on projects.",
    status: null,
  },
];
