// everything i've built, in one place. /software draws the entries that have
// a `canvas` placement as the canvas, in this order; /developer lists every
// entry under its `group`.
//
// an entry: `name`, `href`, a one-line `note`, `status` (null while it still
// runs, else how it ended) and `lang`, its main language. `repo` is the source when `href` is a
// product page. `canvas` places it on the 12-column canvas: `col` (grid
// columns), `drop` (rem from the row above), and the poster's `w` x `h`
// (static/software/<name>.webp). `clip` plays static/previews/<name>.mp4 on
// hover; `phone` gives a phone recording the phone's corners
const GIT = "https://git.harivan.sh/harivansh-afk";

export const groups = {
  software: "things people use",
  tools: "for my own workflow",
  experiments: "built to learn, or to see if it works",
};

export const software = [
  {
    name: "mixbridge",
    lang: "swift",
    group: "software",
    href: "https://mixbridge.app/",
    note: "music streaming with an agent choosing what plays next.",
    status: null,
    canvas: { col: "2 / span 2", drop: 0, w: 590, h: 1280, phone: true, clip: true },
    alt: "mixbridge mixing between two tracks on an iphone",
  },
  {
    name: "touchtips",
    lang: "swift",
    group: "software",
    href: "https://touchtips.app",
    note: "remembers when and where you met everyone in your contacts.",
    status: null,
    canvas: { col: "5 / span 5", drop: 3, w: 1280, h: 720, clip: true },
    alt: "touchtips open on a phone outdoors",
  },
  {
    name: "einstein",
    group: "software",
    href: "https://www.cnet.com/tech/services-and-software/companion-einstein-ai-tool/",
    repo: `${GIT}/einstein`,
    note: "an agent with its own computer that went to class for you.",
    status: "cease and desisted",
    canvas: { col: "11 / span 2", drop: 1, w: 640, h: 400 },
    alt: "einstein's portrait on yellow",
  },
  {
    name: "draw",
    lang: "go",
    group: "software",
    href: `${GIT}/draw`,
    note: "self-hosted excalidraw plus.",
    status: null,
    canvas: { col: "1 / span 6", drop: 1.5, w: 1280, h: 536, clip: true },
    alt: "draw's dashboard of saved canvases",
  },
  {
    name: "roomcast",
    lang: "python",
    group: "software",
    href: `${GIT}/roomcast`,
    note: "text an agent to play a movie on the roku.",
    status: null,
    canvas: { col: "9 / span 2", drop: 0, w: 720, h: 1280, phone: true, clip: true },
    alt: "a telegram message asking an agent to resume a show",
  },
  {
    name: "mux",
    lang: "rust",
    group: "software",
    href: `${GIT}/mux`,
    note: "a terminal multiplexer that is actually a mac app.",
    status: null,
    canvas: { col: "3 / span 4", drop: 2.5, w: 1184, h: 780, clip: true },
    alt: "mux running a nix build across panes",
  },
  {
    name: "deskctl",
    lang: "rust",
    group: "software",
    href: "https://deskctl.dev",
    repo: `${GIT}/deskctl`,
    note: "desktop control for ai agents on x11.",
    status: "no longer maintained",
    canvas: { col: "8 / span 5", drop: 0, w: 1280, h: 652, clip: true },
    alt: "an agent driving a linux desktop through deskctl",
  },
  {
    name: "nap",
    lang: "rust",
    group: "software",
    href: `${GIT}/nap`,
    note: "not airplay: a linux-owned monitor as an extended display for your mac.",
    status: null,
    canvas: { col: "2 / span 2", drop: 0, w: 360, h: 640, phone: true, clip: true },
    alt: "nap casting a mac display to a wall monitor",
  },
  {
    name: "betternas",
    lang: "go",
    group: "software",
    href: "https://betternas.com",
    repo: `${GIT}/betterNAS`,
    note: "remote machines as native finder volumes on your mac.",
    status: "no longer maintained",
    canvas: { col: "5 / span 5", drop: 3.5, w: 1280, h: 800, clip: true },
    alt: "betternas mounting a remote machine in finder",
  },
  {
    name: "pierrejo",
    lang: "javascript",
    group: "software",
    href: `${GIT}/pierrejo`,
    note: "pierre's diff review inside forgejo.",
    status: null,
    canvas: { col: "1 / span 5", drop: 1, w: 1280, h: 894, clip: true },
    alt: "pierrejo rendering a pull request diff in forgejo",
  },
  {
    name: "agentcomputer",
    group: "software",
    href: "https://github.com/AgentComputerAI",
    note: "a vm manager for firecracker, built for agents.",
    status: "no longer maintained",
    canvas: { col: "8 / span 4", drop: 4, w: 1280, h: 782, clip: true },
    alt: "agentcomputer's landing page",
  },
  {
    name: "dueflow",
    group: "software",
    href: "https://www.dueflow.co/",
    note: "dues for student organisations: bill the roster, send reminders, record every payment as it lands.",
    status: null,
    canvas: { col: "3 / span 8", drop: 2, w: 1280, h: 756, clip: true },
    alt: "dueflow's dues dashboard",
  },
  {
    name: "airplay-at-the-crib",
    lang: "swift",
    group: "software",
    href: `${GIT}/airplay-at-the-crib`,
    note: "a mac app that puts roku tvs in screen mirroring on shared wi-fi.",
    status: null,
  },

  {
    name: "cozybox.nvim",
    lang: "lua",
    group: "tools",
    href: `${GIT}/cozybox.nvim`,
    note: "my neovim theme, dark and light. the code on this site wears it.",
    status: null,
  },
  {
    name: "linearjo",
    lang: "typescript",
    group: "tools",
    href: `${GIT}/linearjo`,
    note: "first-class linear integration for forgejo.",
    status: null,
  },
  {
    name: "sim",
    lang: "typescript",
    group: "tools",
    href: `${GIT}/sim`,
    note: "renders markdown and html in the terminal.",
    status: null,
  },
  {
    name: "pending.nvim",
    lang: "lua",
    group: "tools",
    href: `${GIT}/pending.nvim`,
    note: "a pending-task plugin for neovim.",
    status: null,
  },
  {
    name: "forge.nvim",
    lang: "lua",
    group: "tools",
    href: `${GIT}/forge.nvim`,
    note: "a picker-based forge workflow for neovim.",
    status: "archived",
  },
  {
    name: "auto-review-check",
    lang: "shell",
    group: "tools",
    href: `${GIT}/auto-review-check`,
    note: "automates pull request review loops: waits for checks, reads comments, iterates.",
    status: null,
  },
  {
    name: "tmux-subagents",
    lang: "shell",
    group: "tools",
    href: `${GIT}/tmux-subagents`,
    note: "orchestrates cli subagents through tmux windows.",
    status: null,
  },

  {
    name: "llt",
    lang: "svelte",
    group: "experiments",
    href: `${GIT}/llt`,
    note: "low-latency trading: a prediction-market gateway.",
    status: null,
  },
  {
    name: "agentikube",
    lang: "go",
    group: "experiments",
    href: `${GIT}/agentikube`,
    note: "stateful kubernetes pods for ai agents.",
    status: null,
  },
  {
    name: "computer-runtime",
    lang: "shell",
    group: "experiments",
    href: `${GIT}/computer-runtime`,
    note: "a nix bootstrap for declarative agent deployments on agentcomputer.",
    status: null,
  },
  {
    name: "url-shortner",
    lang: "python",
    group: "experiments",
    href: `${GIT}/url-shortner`,
    note: "a distributed url shortener, built to learn.",
    status: null,
  },
  {
    name: "distributed-systems",
    group: "experiments",
    href: `${GIT}/distributed-systems`,
    note: "learning distributed systems through hands-on projects.",
    status: null,
  },
];
